//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCounterApplication.ServiceWordCounter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWordCounter.IWordCounterService")]
    public interface IWordCounterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCounterService/CountWords", ReplyAction="http://tempuri.org/IWordCounterService/CountWordsResponse")]
        long CountWords(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCounterService/CountWords", ReplyAction="http://tempuri.org/IWordCounterService/CountWordsResponse")]
        System.Threading.Tasks.Task<long> CountWordsAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordCounterServiceChannel : WordCounterApplication.ServiceWordCounter.IWordCounterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCounterServiceClient : System.ServiceModel.ClientBase<WordCounterApplication.ServiceWordCounter.IWordCounterService>, WordCounterApplication.ServiceWordCounter.IWordCounterService {
        
        public WordCounterServiceClient() {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCounterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CountWords(string text) {
            return base.Channel.CountWords(text);
        }
        
        public System.Threading.Tasks.Task<long> CountWordsAsync(string text) {
            return base.Channel.CountWordsAsync(text);
        }
    }
}
